epinowcast/epidist

- DESCRIPTION
This PR closes #1. It's very trivial.
- [ x] My PR is based on a package issue and I have explicitly linked it.
- [ x] I have included the target issue or issues in the PR title in the for Issue(s) *issue-numbers*: PR title
- [ x] I have read the [contribution guidelines](https://github.com/epinowcast/.github/blob/main/CONTRIBUTING.md).
- [ x] I have tested my changes locally.
- [ x] I have added or updated unit tests where necessary.
- [ x] I have updated the documentation if required.
- [ x] My code follows the established coding standards.
> Issue 1: Missing comma for remote repository

- .Rbuildignore
- .gitignore
- DESCRIPTION
- R/fitting-and-postprocessing.R
- R/models.R
- R/observe.R
- R/plot-helpers.R
- R/plot.R
- R/preprocess.R
- R/simulate.R
- _pkgdown.yml
This PR starts work on closing #12.
So far I have added a basic version of the `roxygen2` function families.
> Issue 12: Add package website

- tests/testthat/test-multiply.R
This PR closes #24. 
It adds a placeholder unit test. I'm unsure what else is entailed by "testing infrastructure".
> Issue 24: Add placeholder unit test

- README.Rmd
- README.md
This PR closes #10 by removing excess text from the `README` that is not about `epidist`.
> Issue 10: Clean README

- R/simulate.R
- man/epidist-package.Rd
- man/simulate_double_censored_pmf.Rd
- man/simulate_exponential_cases.Rd
- man/simulate_gillespie.Rd
- man/simulate_secondary.Rd
- man/simulate_uniform_cases.Rd
This PR closes #53.
* I have updated the documentation inline with the referenced issue and clarification made by @parksw3
* I have also changed the function arguments to be inline with the writing. That is, using `I0` and `N` rather than `init_I` and `n` in the function
* I have rerendered the `.md` for this function
> Issue 53: Update simulate_gillespie() documentation and argument names

- vignettes/epidist.Rmd
This PR closes #85.
Better or worse versions of explaining how the S3 works could be done. I think eventually will have a good explanation in the "in-depth model (maths and implementation)" vignette which eventually can be pointed to.
> Issue 85: Update get started vignette with S3

- DESCRIPTION
- man/epidist-package.Rd
> Issue 135: Set Adam as maintainer

- DESCRIPTION
- R/latent_individual.R
- tests/testthat/test-unit-latent_individual.R
> Issue 122: Check family input valid

- DESCRIPTION
> Issue 153: Remove here dependency

- README.Rmd
- README.md
This PR closes #156.
I've removed any inaccurate text from the README.
> Issue 156: Remove inaccurate text from README

- tests/testthat/test-int-latent_individual.R
This PR closes #161.
I've added a note about stochastic test fails to every name of a stochastic test. I'm open to better solutions than this.
> Issue 161: Note about stochastic test failure

- R/latent_individual.R
> Issue 99: Informative messaging for priors

- R/latent_individual.R
- tests/testthat/test-unit-latent_individual.R
> Issue 200: Accept strings as family input

- vignettes/faq.Rmd
> Issue 189: Add FAQ on default priors

- R/defaults.R
This PR closes #204.
It turns out that I think actually no where in the code are we using the family class so far, so I removed it.
> Issue 204: Remove family as class

- .github/workflows/check-cmdstan.yaml
This draft PR will close #104.
> Add GitHub action for `cmdstanr`

- tests/testthat/setup.R
- tests/testthat/test-int-latent_individual.R
This draft PR will close issue #180. It will be finished once PR #183 is done.
> Issue 180: Gamma delay convergence and parameter recovery

- DESCRIPTION
- R/defaults.R
- R/generics.R
- R/postprocess.R
- R/prior.R
- man/epidist.Rd
- man/epidist.default.Rd
- tests/testthat/test-int-latent_individual.R
- tests/testthat/test-unit-postprocess.R
- vignettes/faq.Rmd
> Issue 212: Update to priors

- vignettes/faq.Rmd
This PR closes #192.
I felt that just putting this in the FAQ would be OK for now. I think that in future we will probably want a big rewrite of the documentation for the main function `epidist::epidist` that might include perhaps some mention of this (and maybe a link).
> Issue 192: Add FAQ on distributional parameter names

- R/latent_lognormal.R
- tests/testthat/test-unit-predict.R
This PR closes #257.
I followed the approach of e.g. https://github.com/paul-buerkner/brms/blob/ddd34fceee58e1927b3d6885910e009e96c45d83/R/posterior_predict.R#L401.
> Issue 257: Extend prediction functionality to generate multiple draws

- DESCRIPTION
- R/utils.R
- man/floor_mult.Rd
- tests/testthat/test-unit-predict.R
- tests/testthat/test-unit-utils.R
> Issue 256: Allow prediction with no censoring

- R/diagnostics.R
- R/prior.R
- tests/testthat/test-int-latent_individual.R
> Issue 227: Allow setting distributional parameters to constants

- vignettes/approx-inference.Rmd
- vignettes/ebola.Rmd
- vignettes/epidist.Rmd
- vignettes/faq.Rmd
This PR closes #308.
I think this style is a little questionable but that's the price of consistency.
> Issue 308: Use of `::` and linking in vignettes

- vignettes/ebola.Rmd
> Issue 311: Simplify sex recode in Ebola vignette

- R/defaults.R
- R/generics.R
- man/epidist.Rd
- man/epidist.default.Rd
- man/epidist_family.Rd
- man/epidist_family.default.Rd
- man/epidist_formula.Rd
- man/epidist_formula.default.Rd
- man/epidist_stancode.Rd
- man/epidist_stancode.default.Rd
- man/epidist_validate.Rd
- man/epidist_validate.default.Rd
This draft PR will close #166. There is still documentation to add but this might as well go in I think.
> Issue 166: Documentation improvements including of additional arguments

- R/globals.R
- R/latent_individual.R
- tests/testthat/test-latent_individual.R
This PR closes #320.
It also runs `document` so could be used so we don't need PR #324.
> Issue #320: Rename delay central

- _pkgdown.yml
> Issue #333: Use mathjax

- vignettes/ebola.Rmd
- vignettes/epidist.Rmd
- vignettes/faq.Rmd
> Issue #339: Add internal function linking in vignettes

- _pkgdown.yml
This PR closes #350. (Self explanatory.)
> Issue #350: Remove utility functions `pkgdown` section

- DESCRIPTION
- _pkgdown.yml
This PR closes #368. Moves author list in `DESCRIPTION` and in bottom bar I think.
> Issue #368: Reorder author list on website

- R/diagnostics.R
- man/epidist_diagnostics.Rd
- vignettes/faq.Rmd
This PR closes #376.
Self explanatory / small change.
> Issue #376: Add `epidist_diagnostics` to FAQ

- DESCRIPTION
- vignettes/faq.Rmd
- vignettes/references.bib
This PR closes #391.
Self-explanatory / short PR.
If a package is mentioned in FAQ does it need to be in Suggests?
> Issue #391: Add `priorsense` to FAQ

- vignettes/faq.Rmd
This PR will close #394. Self explanatory.
> Issue #394: Add information about predictions to FAQ

- DESCRIPTION
- README.Rmd
- README.md
- man/epidist-package.Rd
This PR closes #401. Self-explanatory.
> Issue #401: Change package description

- README.Rmd
- README.md
- vignettes/references.bib
This PR closes #408. Self explained.
> Issue #408: Update to PLOS CB version of Charniga et al.

- R/naive_model.R
- _pkgdown.yml
- man/as_epidist_naive_model.Rd
- man/as_epidist_naive_model.epidist_linelist_data.Rd
- tests/testthat/setup.R
- tests/testthat/test-int-direct_model.R
- tests/testthat/test-naive_model.R
This PR closes #445. Self explained.
I control F for "individual" and didn't find any to fix. I think I've fixed the "direct" ones.
> Issue #445: Complete rename of models

- README.Rmd
> Issue #453: Remove warning on README about stability

- NEWS.md
This PR drafts the relase NEWS for #425.
> Issue #425: Add release NEWS

- _pkgdown.yml
This PR closes #451. Self explained. Adds issue https://github.com/epinowcast/epidist/issues/457.
The order is now:
```
reference:
- title: Linelist data
- title: Model fitting
- title: Naive model
- title: Latent model
- title: Postprocess
- title: Diagnostic functions
- title: Assert validity of objects
- title: Family
- title: Formula
- title: Prior distributions
- title: Stan code
- title: Simulation
- title: Data
- title: Reexported functions
```
> Issue #451: Reorder function sections on website

- README.Rmd
> Remove --> previously used to comment out in `README.Rmd`

- vignettes/ebola.Rmd
> Function display fix in Ebola vignette

- DESCRIPTION
- NEWS.md
As the title this PR closes #504.
> Issue #504: Use patched primarycensored without size()

- DESCRIPTION
- NEWS.md
This PR closes #521 by updating the maintainer as discussed in that issue.
> Issue #521: Change maintainer

- _pkgdown.yml
This PR closes #<issue-number>.
[Describe the changes that you made in this pull request.]
> Update _pkgdown.yml - add news

- vignettes/approx-inference.Rmd
- vignettes/epidist.Rmd
This PR closes #544 
line 84 recive -> receive in epidist.Rmd
line 49 the -> is in approx-inference.Rmd
> Issue #544: fixing minor typos in 2 vignettes

- vignettes/epidist.Rmd
This PR closes #552 .
I moved up the refs to the top of the getting started vignette and enclosed them in a banner.
> Issue #552: Better signposting for refs
