epinowcast/epidist

R/fitting-and-postprocessing.R, R/models.R, R/observe.R, R/plot-helpers.R, R/plot.R, R/preprocess.R, R/simulate.R, vignettes/epidist.Rmd
This PR closes #3 .
- I got rid of all instances of DT and replaced them with standard data.table uses. I tested that the vignette gives sensible answers.
- Also updated the vignette file to remove the use of DT.
=> Issue 3: Not using DT.

DESCRIPTION, R/fitting-and-postprocessing.R, R/observe.R, R/plot-helpers.R, R/preprocess.R
This PR closes https://github.com/epinowcast/epidist/issues/17.
It adds some missing assignments, based on looking through https://github.com/epinowcast/epidist/issues/3 and correcting the issues that I can spot.
As the package doesn't have testing (I think) I'm unsure about how I can test my changes (or be sure that I've got all of them). Open to suggestions on how to do this. Could be that we should move forward on #5 as a priority.
=> Issue 17: Fixes to data.table assignment

.github/workflows/R-CMD-check.yaml, .github/workflows/build-and-push-image.yaml, .github/workflows/pkgdown.yaml, .github/workflows/test-coverage.yaml
This PR is not linked to an issue. It overhauls the current CI to better match practice in `epinowcast` (mostly this is using our `cmdstan` action which has caching to speed up builds of CI) in order to begin looking at the issue with the `pkgdown` docs. With the same aim in mind it also adds saving the built website as an enviroment object (which is not standard `epinowcast` practice but should imo).
=> Add epinowcast/actions/install-cmdstan + pgdown as env object

DESCRIPTION, vignettes/epidist.Rmd, vignettes/references.bib
This PR will close #9.
It is a draft of a rewritten version of the first "Get started" vignette.
=> Issue 9: Getting started vignette

.github/workflows/render-readme.yaml
This PR will close issue #29.
So far, I have copied exactly the file https://github.com/epinowcast/epinowcast/blob/main/.github/workflows/render-readme.yaml from `epinowcast` to here.
I don't have a very good understanding of these `.yaml` workflow files yet, so @seabbs if you could give me some guidance on what to change here to get this working, that'd be great. (Happy to have a short call about it if easier!)
Ideally this would serve as a learning opportunity for me to be more confident to make these sorts of edits in future.
=> Issue 29: Update README workflow

DESCRIPTION, vignettes/epidist.Rmd
=> Issue 57: Polish get started vignette

R/globals.R, R/latent_individual.R, R/simulate.R
This PR closes #116.
I have checked that I have all of them by searching for `NULL` in the GitHub repo. I don't think there would be any that would miss, but could be wrong (?).
=> Issue 116: Missing roxyglobals

DESCRIPTION, tests/testthat/helper-expectations.R
This PR closes #134.
To do this I used `brms` functions to get the maximum treedepth and number of divergent transitions rather than `rstan`.
=> Issue 134: Drop rstan dependency

DESCRIPTION, R/latent_individual.R, tests/testthat/test-unit-latent_individual.R
This PR closes #118.
I have checked the formula input is a formula and the variables are in the data. I used `cli` and added it to `DESCRIPTION`. I've also put the unit test for this back, which should pass now.
=> Issue 118: Check formula input

tests/testthat/test-int-latent_individual.R
This PR closes #130.
I have checked that rerunning the fitting code produces the same e.g. p-values if you have both these seeds set. This should mean that the stochastic tests will now only change when directly changed (and then continue to produce the same answers).
This means that it's possible a change is made which is correct, but will repeatedly fail the CI. Making new issue for this (#161).
=> Issue 130: Set seeds for integration tests

tests/testthat/test-int-latent_individual.R
This PR closes #127.
I have added an issue about the complexity with where the invalid code comes from https://github.com/epinowcast/epidist/issues/159.
=> Issue 127: Check Stan code is valid syntax

vignettes/approx-inference.Rmd
This fixes the appearance of the `times (s)` column in the `approx-inference` vignette (see screenshots). I also made the code a bit more compact.
Closes https://github.com/epinowcast/epidist/issues/185.
Before:
After:
=> Issue 185: Streamline and fix table in approx-inference vignette

DESCRIPTION, _pkgdown.yml, vignettes/faq.Rmd
This draft PR will close #174.
=> Issue 174: Add FAQ website section

R/diagnostics.R, R/generics.R, R/latent_individual.R, R/latent_lognormal.R, R/postprocess.R, R/prior.R, R/utils.R, man/as_latent_individual.Rd, man/epidist.Rd, man/epidist.default.Rd, man/epidist_diagnostics.Rd, man/epidist_family_prior.Rd, man/epidist_family_prior.default.Rd, man/epidist_family_prior.lognormal.Rd, man/epidist_formula.epidist_latent_individual.Rd, man/epidist_model_prior.Rd, man/epidist_model_prior.default.Rd, man/epidist_prior.Rd, man/epidist_stan_chunk.Rd, man/epidist_version_stanvar.Rd, man/floor_mult.Rd, man/posterior_epred_latent_lognormal.Rd, man/posterior_predict_latent_lognormal.Rd, man/predict_delay_parameters.Rd, man/replace_prior.Rd
This PR closes #216. As well as the hyperlinks, I also made some small text improvements to the documentation of the package (mostly the priors file).
=> Issue 216: Use `[pkg::func()]` in roxygen comments everywhere

R/postprocess.R, tests/testthat/setup.R, tests/testthat/test-unit-postprocess.R
This PR closes #270.
It:
* Fixes a bug with `predict_delay_parameters`
* Adds test data with a strata level difference, allowing testing that the function works (the bug was related to wrong indexing of predictions)
Arguably, we will be cutting `predict_delay_parameters` soon so why add this.
1. It's better that it works for the time being
2. We can probably reuse parts of the test data which has a difference by strata in new tests for the prediction
3. Maybe we won't cut `predict_delay_parameters` but refactor to use internal `tidybayes`
=> Issue 270: Correct bug with `predict_delay_parameters`

R/latent_gamma.R, R/latent_lognormal.R
This PR is unlinked to an issue. In reviewing the current functionality needed for a family I slightly simplified the current code.  
Unrelated to this PR there are lots of ways we can streamline adding families and sharing support across models and across families (for models) it looks like which is great.
=> Simplify epred

vignettes/ebola.Rmd
This PR closes #319.
As well as making the figure bigger I:
* Fixed a bug with `after_stat` and `facet_grid` giving wrong density histograms
* Recoded the districts to put a new line in two word names for the figure
* Fixed some issues with the vignette title
=> Issue #319: Fixes to Ebola vignette sex-district figures

vignettes/ebola.Rmd
=> Issue #332: Fix to `R CMD CHECK` on Windows by reverting family as string in Ebola vignette

README.Rmd
This PR closes #347. It moves to using a badge that is explicitly for `main` vs depending on the defaults.
=> Issue #347: Use badge explicity for main branch

R/family.R, R/fit.R, R/formula.R, R/prior.R, R/stancode.R, R/validate.R, man/dot-add_dpar_info.Rd, man/epidist.Rd, man/epidist.default.Rd, man/epidist_family.Rd, man/epidist_family_model.Rd, man/epidist_family_model.default.Rd, man/epidist_family_model.epidist_latent_individual.Rd, man/epidist_family_prior.Rd, man/epidist_family_prior.default.Rd, man/epidist_family_prior.lognormal.Rd, man/epidist_family_reparam.Rd, man/epidist_family_reparam.default.Rd, man/epidist_family_reparam.gamma.Rd, man/epidist_formula.Rd, man/epidist_formula_model.default.Rd, man/epidist_model_prior.Rd, man/epidist_model_prior.default.Rd, man/epidist_prior.Rd, tests/testthat/test-int-latent_individual.R, tests/testthat/test-prior.R
This PR closes #298.
Changes made:
* Move lines that are called in `epidist_family_prior.class` into `epidist_family` if they are independent of `class`
* Remove adding class to object in `epidist_family` because `epidist_family` already does it
* Set `epidist_prior` to take `epidist_family` as input rather than `family`
* Alter documentation to be clearer about `family` and `epidist_family`, `formula` and `epidist_formula`, ...
* Fixes to tests...
Warrants future issues:
* I think after we get the processing in we need to go through e.g. `latent_individual.R` and fix the documentation. Right now it's a bit of a mess
=> Issue #298: `epidist_prior` accepting output of `epidist_family` and improved argument documentation

R/fit.R, man/epidist.Rd, man/epidist.default.Rd, tests/testthat/test-formula.R, tests/testthat/test-int-latent_individual.R, vignettes/ebola.Rmd, vignettes/faq.Rmd
This PR closes #374.
I think we already had things set up to work fine with `formula = mu ~ 1` because `epidist_formula` is calling:
```r
formula <- brms:::validate_formula(formula, data = data, family = family)
```
So it already is going to convert from `mu ~ 1` to ` brms::bf`.
I added one unit test to check this.
Edit: this unit test was later removed in favour of using `mu ~ 1` as the default.
=> Issue #374: Set default to `mu ~ 1` as formula

tests/testthat/_snaps/utils.md, tests/testthat/test-utils.R
This PR closes #194.
So far it adds a snapshot test for expecting a certain warning.
There are also lots of calls to `expect_error`. I wonder how they should be handled? New issue for this?
=> Issue #194: Update tests to expect particular warnings

R/simulate.R, man/simulate_secondary.Rd
This PR closes #381.
The only case where something is called linelist are this simulation function, and the `observe_process` function. We are expecting to remove `observe_process` with issue #431.
=> Issue #381: Rename linelist argument to data

.github/workflows/R-CMD-check.yaml
This is a draft PR to test if we still have R CMD CHECK issues on Mac (#120).
Edit: it worked! That's excited. What has my life come to that I am excited by that.
=> Issue #120: Add Mac OS to R CMD CHECK

vignettes/approx-inference.Rmd, vignettes/ebola.Rmd, vignettes/epidist.Rmd, vignettes/faq.Rmd
This PR closes #430. I made a few edits to the vignettes but have left the issues outstanding about using the naive model (#403) and adding a figure about right truncation (#56).
=> Issue #430: Proofread and update vignettes for release

vignettes/epidist.Rmd
=> Issue #491: Update vignette text to refer to the marginal model.

NEWS.md
This PR closes #480.
Using find in files I didn't find other instances of the full word "stan" that should be replaced.
=> Issue #480: Use "Stan" not "stan"

.pre-commit-config.yaml, NEWS.md, R/marginal_model.R, README.Rmd, man/as_epidist_marginal_model.epidist_linelist_data.Rd, tests/testthat/setup.R, tests/testthat/test-gen.R, tests/testthat/test-int-direct_model.R, tests/testthat/test-int-latent_model.R, tests/testthat/test-marginal_model.R
This PR closes #507 by adding weighting support to the linelist method for the marginal model. This allows you to seamlessly use aggregate data for the marginal model. It is a component of #412.
=> Issue #507: Add weighting support to marginal model class

.github/workflows/R-CMD-as-cran-check.yaml, .github/workflows/R-CMD-check.yaml, .github/workflows/check-cmdstan.yaml, .github/workflows/lint-changed-files.yaml, .github/workflows/pkgdown.yaml, .github/workflows/render-readme.yaml, .github/workflows/test-coverage.yaml, DESCRIPTION
This PR closes #503 by swapping to use the github version of cmdstanr. This has the knock on effect of using the CRAN version vs the universe version of rstan on the CI which is the actual issue as far as I can tell.
[Describe the changes that you made in this pull request.]
=> Issue #503: Fix windows CI

NEWS.md, vignettes/approx-inference.Rmd, vignettes/ebola.Rmd, vignettes/epidist.Rmd
This PR closes #532. Turns off vignette caching to check the full build of all vignettes in CI and pkgdown.
=> Issue #532: Remove caching

vignettes/model.Rmd, vignettes/references.bib
This PR closes #554. Self-explained.
Pre-commit is currently failing everywhere. Considering new issue / fix.
=> Issue #554: Model vignette fixes
